docker:
  image: cirrusci/flutter:stable
  as_root: true
architect:
  - rafamizes
merge:
  script:
    - echo "testing..."
    - flutter clean
    - flutter pub get
    - flutter test
  squash: true
  fast-forward: default
