architect:
  - rafamizes
docker:
  image: ubuntu:latest
install:
  - cd ..
  - git clone https://github.com/flutter/flutter.git -b stable
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
  - cd -
merge:
  script:
    - flutter pub clean
    - flutter pub get
    - flutter test
    - flutter pub publish --dry-run
