language: dart
dart:
# min. specific stable release with Null Safety feature.
- "2.12.0"
dart_task:
# analyzer task commented out because flutter will perform the code analyzes.
# - dartanalyzer: --fatal-warnings

# Dart formatter verifies whether all files are correctly formatted.
- dartfmt -n lib/ test/ example/
# The matrix option on Travis lets us set up multiple test runs that will perform in parallel.t
matrix:
  include:
    - name: Test
      env: COMMAND=test --coverage
    - name: Analyze
      env: COMMAND=analyze
addons:
  apt:
    packages: 
      - lib32stdc++6 # so that flutter doctor won't complain.
      - fonts-droid-fallback
install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
  - gem install coveralls-lcov
script:
  - cd app
  - ./flutter/bin/flutter $COMMAND
after_success:
  - coveralls-lcov coverage/lcov.info
cache:
  directories:
    - $HOME/.pub-cache
