language: dart
dart:
# min. specific stable release with Null Safety feature.
- stable
os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # you need this source to get the right version of libstdc++6
    packages:
      - libstdc++6
install:
  - echo 'Avoid default Travis CI install step' # this is to avoid an error with pub in Travis
  - gem install coveralls-lcov
before_script:
  - cd ..
  - git clone https://github.com/flutter/flutter.git -b stable
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
script:
  - cd $TRAVIS_BUILD_DIR
  - dartfmt -n lib test example 
  - flutter packages get
  - flutter analyze --no-pub --no-current-package lib test example
  - flutter test --coverage
  - flutter packages pub publish --dry-run
after_success:
  - coveralls-lcov coverage/lcov.info
cache:
  directories:
    - $HOME/.pub-cache
