language: dart
dart:
- "2.12.0" # specific stable release.
dart_task:
- dartanalyzer: --fatal-warnings
- dartfmt
addons:
  apt:
    packages: # so that flutter doctor won't complain.
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
  - gem install coveralls-lcov
script:
  - ./flutter/bin/flutter test --coverage
after_success:
  - coveralls-lcov coverage/lcov.info
cache:
  directories:
    - $HOME/.pub-cache
