name: flutter_brand_palettes
description: A collection of elegant, declarative classes for the color palettes of popular brands and companies.
version: 0.5.0
homepage: https://dartoos.dev
repository: https://github.com/dartoos-dev/flutter_brand_palettes

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  eo_color: ^2.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
