name: flutter_brand_palettes
description: Set of declarative classes for the official color palettes of popular brands and companies. In addition, this package provides classes for the Material Design's color palettes, such as "Grey", "BlueGrey", "Green", "GreenAccent", and so on.
version: 0.1.8
homepage: https://github.com/rafamizes/flutter_brand_palettes

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
