name: flutter_brand_palettes
description: Collection of elegant and declarative classes for the color palettes and official logos of popular brands and companies.
version: 0.3.0
homepage: https://dartoos.dev
repository: https://github.com/rafamizes/flutter_brand_palettes

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  eo_color: ^0.0.9
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
